Repository GTNewHorizons/Applied-Energistics-2-Unofficial, pull requests merged in 2024-12, with the labels that each got.

#620 Feature: option to hide "stored" items in ae2 crafting plan
  src/main/java/appeng/api/config/Settings.java
  src/main/java/appeng/client/gui/implementations/GuiCraftingCPU.java
  src/main/java/appeng/client/gui/implementations/GuiCraftingStatus.java
  src/main/java/appeng/client/gui/widgets/GuiImgButton.java
  src/main/java/appeng/core/AEConfig.java
  src/main/java/appeng/core/localization/ButtonToolTips.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
  src/main/resources/assets/appliedenergistics2/textures/guis/states.png
Labels: new feature

#622 Add fake crafting card for AE
  src/main/java/appeng/api/config/Upgrades.java
  src/main/java/appeng/api/definitions/IMaterials.java
  src/main/java/appeng/core/Registration.java
  src/main/java/appeng/core/api/definitions/ApiMaterials.java
  src/main/java/appeng/helpers/DualityInterface.java
  src/main/java/appeng/items/materials/ItemMultiMaterial.java
  src/main/java/appeng/items/materials/MaterialType.java
  src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java
  src/main/java/appeng/parts/automation/UpgradeInventory.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
  src/main/resources/assets/appliedenergistics2/lang/zh_CN.lang
  src/main/resources/assets/appliedenergistics2/textures/items/ItemMaterial.CardFakeCrafting.png
Labels: new feature

#617 Add Superluminal Acceleration Card for IOPort
  src/main/java/appeng/api/config/Upgrades.java
  src/main/java/appeng/api/definitions/IMaterials.java
  src/main/java/appeng/core/Registration.java
  src/main/java/appeng/core/api/definitions/ApiMaterials.java
  src/main/java/appeng/items/materials/ItemMultiMaterial.java
  src/main/java/appeng/items/materials/MaterialType.java
  src/main/java/appeng/parts/automation/UpgradeInventory.java
  src/main/java/appeng/tile/storage/TileIOPort.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
  src/main/resources/assets/appliedenergistics2/textures/items/ItemMaterial.CardSuperluminalSpeed.png
Labels: new feature

#626 Make "unusable" IO port modes useful & add cell movement queue
  src/main/java/appeng/tile/storage/TileIOPort.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
Labels: enhancement

#646 Fix IO port early returning before processing queue
  src/main/java/appeng/tile/storage/TileIOPort.java
Labels: bug, Fix
