Repository GTNewHorizons/Applied-Energistics-2-Unofficial, pull requests merged in 2025-08, with the labels that each got.

#808 Add `ItemImmutableList` for immutable item collection management
  dependencies.gradle
  src/main/java/appeng/api/storage/IStorageHelper.java
  src/main/java/appeng/api/storage/data/IDisplayRepo.java
  src/main/java/appeng/api/storage/data/IItemList.java
  src/main/java/appeng/client/gui/implementations/GuiMEMonitorable.java
  src/main/java/appeng/client/me/ItemRepo.java
  src/main/java/appeng/core/api/ApiStorage.java
  src/main/java/appeng/core/sync/packets/PacketNEIRecipe.java
  src/main/java/appeng/util/item/ItemImmutableList.java
Labels: :construction: Testing on Zeta

#828 Show Correctly Required Power in SpatialIO
  src/main/java/appeng/client/gui/implementations/GuiNetworkStatus.java
  src/main/java/appeng/container/implementations/ContainerSpatialIOPort.java
Labels: bugfix

#824 Middle click craft ordering inserts a proper count
  src/main/java/appeng/client/gui/implementations/GuiCraftAmount.java
  src/main/java/appeng/client/gui/implementations/GuiCraftingCPU.java
  src/main/java/appeng/client/gui/implementations/GuiPriority.java
  src/main/java/appeng/container/implementations/ContainerCraftAmount.java
  src/main/java/appeng/container/implementations/ContainerPriority.java
  src/main/java/appeng/core/sync/packets/PacketInventoryAction.java
Labels: enhancement

#832 Remove debug log
  src/main/java/appeng/container/AEBaseContainer.java
Labels: safe for stable

#839 Re-add the client only annotation to ContainerPriority but without a default value to avoid server-side exceptions
  src/main/java/appeng/container/implementations/ContainerPriority.java
Labels: Fix

#838 Remove error log from CellInventory as it can lead to log spam
  src/main/java/appeng/me/storage/CellInventory.java
Labels: Fix

#835 Fix duping and voiding bug on network changes in p2p interface
  src/main/java/appeng/parts/p2p/PartP2PInterface.java
Labels: Fix
