Repository GTNewHorizons/Applied-Energistics-2-Unofficial, pull requests merged in 2025-03, with the labels that each got.

#690 Redo self powered me controller textures
  src/main/resources/assets/appliedenergistics2/textures/blocks/BlockCreativeEnergyController.png
  src/main/resources/assets/appliedenergistics2/textures/blocks/BlockCreativeEnergyControllerColumn.png
  src/main/resources/assets/appliedenergistics2/textures/blocks/BlockCreativeEnergyControllerColumnPowered.png
  src/main/resources/assets/appliedenergistics2/textures/blocks/BlockCreativeEnergyControllerInsideA.png
  src/main/resources/assets/appliedenergistics2/textures/blocks/BlockCreativeEnergyControllerInsideB.png
  src/main/resources/assets/appliedenergistics2/textures/blocks/BlockCreativeEnergyControllerPowered.png
Labels: enhancement

#697 Expansion of Quick Cell Partitioning (And a bugfix)
  src/main/java/appeng/api/implementations/tiles/IChestOrDrive.java
  src/main/java/appeng/block/storage/BlockChest.java
  src/main/java/appeng/block/storage/BlockDrive.java
  src/main/java/appeng/core/localization/PlayerMessages.java
  src/main/java/appeng/items/materials/ItemMultiMaterial.java
  src/main/java/appeng/items/storage/ItemBasicStorageCell.java
  src/main/java/appeng/items/storage/ItemExtremeStorageCell.java
  src/main/java/appeng/tile/storage/TileChest.java
  src/main/java/appeng/tile/storage/TileDrive.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
Labels: :construction: Testing on Zeta

#695 Remove stack capture from GridAccessException
  src/main/java/appeng/core/AEConfig.java
  src/main/java/appeng/me/GridAccessException.java
Labels: bug
