Repository GTNewHorizons/Applied-Energistics-2-Unofficial, pull requests merged in 2025-06, with the labels that each got.

#762 Cells tooltip displays the number of filters used
  src/main/java/appeng/items/storage/ItemBasicStorageCell.java
Labels: :construction: Testing on Zeta

#739 Always try distribute (same) patterns between interfaces
  src/main/java/appeng/api/networking/crafting/ICraftingMedium.java
  src/main/java/appeng/client/gui/implementations/GuiCraftingCPU.java
  src/main/java/appeng/container/implementations/ContainerCraftingCPU.java
  src/main/java/appeng/core/sync/packets/PacketCraftingItemInterface.java
  src/main/java/appeng/helpers/DualityInterface.java
  src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java
  src/main/java/appeng/util/ScheduledReason.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
Labels: :construction: Testing on Zeta

#776 Fix CompassService waiting for tasks on world stop
  src/main/java/appeng/services/CompassService.java
Labels: bugfix

#773 Added a Baubles Slot for the Wireless Terminal
  dependencies.gradle
  src/main/java/appeng/core/AppEng.java
  src/main/java/appeng/items/tools/powered/ToolWirelessTerminal.java
  src/main/resources/assets/baubles/textures/items/empty_bauble_slot_Terminal.png
Labels: :construction: Testing on Zeta

#780 Reduce ME Chest Display Updates
  src/main/java/appeng/tile/storage/TileChest.java
Labels: Fix, :construction: Testing on Zeta, safe for stable

#703 Highlight network machine in world with shift click in network tool gui and open machine gui through network tool
  src/main/java/appeng/api/util/DimensionalCoord.java
  src/main/java/appeng/api/util/NamedDimensionalCoord.java
  src/main/java/appeng/client/gui/implementations/GuiNetworkStatus.java
  src/main/java/appeng/client/gui/widgets/GuiContextMenu.java
  src/main/java/appeng/client/render/BlockPosHighlighter.java
  src/main/java/appeng/container/implementations/ContainerNetworkStatus.java
  src/main/java/appeng/core/localization/PlayerMessages.java
  src/main/java/appeng/items/tools/ToolAdvancedNetworkTool.java
  src/main/java/appeng/items/tools/ToolNetworkTool.java
  src/main/java/appeng/tile/AEBaseInvTile.java
  src/main/resources/assets/appliedenergistics2/lang/en_US.lang
Labels: :construction: Testing on Zeta

#766 Fix bug when on merge you got weird behavior
  src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java
Labels: :construction: Testing on Zeta

#759 Make P2P Tunnel - ME Interface share storage slot contents between input and outputs
  src/main/java/appeng/client/gui/implementations/GuiInterface.java
  src/main/java/appeng/container/implementations/ContainerInterface.java
  src/main/java/appeng/container/slot/OptionalSlotFake.java
  src/main/java/appeng/helpers/DualityInterface.java
  src/main/java/appeng/parts/p2p/PartP2PInterface.java
  src/main/resources/assets/appliedenergistics2/textures/guis/interfacenonenoconfig.png
Labels: :construction: Testing on Zeta

#786 fix terminals gone
  src/main/java/appeng/items/contents/PinsHolder.java
Labels: Fix, :construction: Testing on Zeta
